disabled_rules:
- line_length
- switch_case_alignment
- type_name
- multiple_closures_with_trailing_closure
- trailing_comma
opt_in_rules:
- empty_count
- empty_string
excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib
- CovidWatch/*/*.pb.swift
- DerivedData
function_body_length:
    warning: 300
    error: 500
function_parameter_count:
    warning: 6
    error: 8
type_body_length:
    warning: 300
    error: 500
file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
cyclomatic_complexity:
    warning: 15
    error: 25
identifier_name:
  allowed_symbols: "_"
  validates_start_with_lowercase: false
  min_length: 1
  max_length:
    warning: 90
    error: 1000
  excluded:
    - id
reporter: "xcode"
