//
//  Created by Zsombor Szabo on 10/05/2020.
//  
//

import SwiftUI

struct ReportingFinish: View {
    
    var body: some View {
        
        ZStack(alignment: .top) {
            
            ScrollView(.vertical, showsIndicators: false) {
                
                VStack(spacing: 0) {
                    
                    Spacer(minLength: .headerHeight)
                    
                    Text("Thank You for Sharing Your Positive Diagnosis")
                        .modifier(StandardTitleTextViewModifier())
                        .padding(.horizontal, 2 * .standardSpacing)
                        .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .leading)
                    
                    Image("Family Earth")
                        .padding(.top, 2 * .standardSpacing)
                        .padding(.bottom, 2 * .standardSpacing)
                    
                    Text("Content generated by Sample Health Authority: Viverra bibendum tellus sed dolor, non non, id. At justo, in imperdiet vitae, tempor accumsan. Nulla lobortis in aliquam leo, tincidunt augue pellentesque.")
                        .font(.custom("Montserrat-Regular", size: 16))
                        .foregroundColor(Color("Title Text Color"))
                        .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .leading)
                        .padding(.horizontal, 2 * .standardSpacing)
                    
                    Button(action: {
                        ApplicationController.shared.shareApp()
                    }) {
                        Text("Share the App").modifier(SmallCallToAction())
                    }
                    .padding(.top, 2 * .standardSpacing)
                    .padding(.horizontal, 2 * .standardSpacing)
                    
                    Image("Powered By CW Grey")
                        .accessibility(label: Text("POWERED_BY_CW_IMAGE_ACCESSIBILITY_LABEL"))
                        .padding(.top, 2 * .standardSpacing)
                        .padding(.bottom, .standardSpacing)
                }
            }
            
            HeaderBar(showMenu: false, showDismissButton: true)
        }
    }
}

struct ReportingFinish_Previews: PreviewProvider {
    static var previews: some View {
        ReportingFinish()
    }
}
